# Generated by Django 5.0.6 on 2024-06-27 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_contributorprofile_studentprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributorprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Contributor",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="ContributorProfile",
        ),
        migrations.DeleteModel(
            name="StudentProfile",
        ),
    ]
