# Generated by Django 5.0.6 on 2024-07-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_contributorprofile_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("MODERATOR", "Moderator"),
                    ("STUDENT", "Student"),
                    ("CONTRIBUTOR", "Contributor"),
                ],
                max_length=50,
            ),
        ),
    ]
