# Generated by Django 5.0.6 on 2024-07-01 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 1, 19, 39, 5, 372035, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
