# Generated by Django 5.0.6 on 2024-07-01 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_alter_review_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 1, 19, 39, 58, 837649, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
