# Generated by Django 5.0.6 on 2024-07-02 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_alter_review_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 2, 12, 48, 18, 80228, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
