# Generated by Django 5.0.6 on 2024-07-02 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_content_title_alter_content_created_at"),
        ("review", "0006_alter_review_created_at"),
        ("student", "0002_studentprofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="content.content"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="student.student"
            ),
        ),
    ]
