# Generated by Django 5.0.6 on 2024-07-02 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_alter_content_user"),
        ("review", "0007_alter_review_content_alter_review_student"),
        ("student", "0002_studentprofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="content.content",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="student.student",
            ),
        ),
    ]
