# Generated by Django 5.0.6 on 2024-07-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0008_alter_review_content_alter_review_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=0,
            ),
        ),
    ]
