# Generated by Django 5.0.6 on 2024-07-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributorprofile",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="contr_pics"),
        ),
    ]
