# Generated by Django 5.0.6 on 2024-07-01 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_content_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 1, 16, 9, 52, 732943, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
