# Generated by Django 5.0.6 on 2024-07-02 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_alter_content_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 2, 8, 31, 38, 815669, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
