# Generated by Django 5.0.6 on 2024-07-02 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_content_title_alter_content_created_at"),
        ("contributor", "0002_contributorprofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="contributor.contributor",
            ),
        ),
    ]
