# Generated by Django 5.0.6 on 2024-07-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_category_savedcontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
