# Generated by Django 5.0.6 on 2024-07-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_content_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="approved",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Not Approved", "Not Approved"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
