# Generated by Django 5.0.6 on 2024-07-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_moderatedcontent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="category",
        ),
        migrations.AddField(
            model_name="content",
            name="categories",
            field=models.ManyToManyField(
                related_name="contents", to="content.category"
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="categories_str",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
